### PR TITLE
VirusTotal Module

### PR DESCRIPTION
**Pull request by 3c7**
This PR aims to add support for the VirusTotal module.

### CODE REVIEW

**Comment by 3c7** [comment]
This PR is now ready for review. Along the VT module definition, an additional test case was assed with some example Yara rules found in the VT documentation.

**Comment by metthal** [comment]
Sorry for the very late reaction, we recently discussed what to do with this PR since VT module is not officially available (unfortunately) but we decided that it'd probably be best if we actually have it in our codebase so let's run tests and merge it.

**Comment by metthal** [comment]
The test failure is not your mistake, it's something on our side. I'll resolve it.

**Comment by 3c7** [comment]
There's one PR on my side which implements more filetypes I'd like to merge before you continue. I missed it before but it's super useful.

**Comment by 3c7** [comment]
Ready to merge from my side.

**Comment by metthal** [comment]
Thanks. I'll postpone the merge for now though cause there are some issues on master branch. I'm trying to resolve those first and then I'll get back to you.

**Comment by metthal** [comment]
Could you just please rebase the PR so that tests actually run? Master already contains fix of the Windows tests. Thanks

**Comment by metthal** [comment]
Okay I actually found out I can rebase your PR branch so I did it.

**Pull request merged**
